-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 01:31:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mcFaddan
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mcfaddan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mcfaddan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mcfaddan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mcfaddan` ;

-- -----------------------------------------------------
-- Table `mcfaddan`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`administrator` (
  `adminID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `passwordHash` VARCHAR(255) NULL DEFAULT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`adminID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mcfaddan`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`category` (
  `categoryID` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`categoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mcfaddan`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`member` (
  `memberID` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `userName` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `passwordHash` VARCHAR(255) NULL DEFAULT NULL,
  `salt` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`memberID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mcfaddan`.`memberaddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`memberaddress` (
  `addressID` INT NOT NULL AUTO_INCREMENT,
  `memberID` INT NULL DEFAULT NULL,
  `address1` VARCHAR(255) NULL DEFAULT NULL,
  `address2` VARCHAR(255) NULL DEFAULT NULL,
  `address3` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `county` VARCHAR(255) NULL DEFAULT NULL,
  `eircode` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`addressID`),
  INDEX `memberID` (`memberID` ASC) VISIBLE,
  CONSTRAINT `memberaddress_ibfk_1`
    FOREIGN KEY (`memberID`)
    REFERENCES `mcfaddan`.`member` (`memberID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mcfaddan`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`orders` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `memberID` INT NULL DEFAULT NULL,
  `orderDate` DATETIME NULL DEFAULT NULL,
  `shippingCost` DECIMAL(10,2) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `memberID` (`memberID` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`memberID`)
    REFERENCES `mcfaddan`.`member` (`memberID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mcfaddan`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`product` (
  `productID` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `imagePath` VARCHAR(255) NULL DEFAULT NULL,
  `stockQuantity` INT NULL DEFAULT NULL,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `categoryID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`productID`),
  INDEX `categoryID` (`categoryID` ASC) VISIBLE,
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`categoryID`)
    REFERENCES `mcfaddan`.`category` (`categoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mcfaddan`.`orderdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`orderdetail` (
  `orderDetailID` INT NOT NULL AUTO_INCREMENT,
  `orderID` INT NULL DEFAULT NULL,
  `productID` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`orderDetailID`),
  INDEX `orderID` (`orderID` ASC) VISIBLE,
  INDEX `productID` (`productID` ASC) VISIBLE,
  CONSTRAINT `orderdetail_ibfk_1`
    FOREIGN KEY (`orderID`)
    REFERENCES `mcfaddan`.`orders` (`orderID`),
  CONSTRAINT `orderdetail_ibfk_2`
    FOREIGN KEY (`productID`)
    REFERENCES `mcfaddan`.`product` (`productID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mcfaddan`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`payment` (
  `paymentID` INT NOT NULL AUTO_INCREMENT,
  `orderID` INT NULL DEFAULT NULL,
  `paymentDate` DATETIME NULL DEFAULT NULL,
  `totalAmount` DECIMAL(10,2) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`paymentID`),
  INDEX `orderID` (`orderID` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`orderID`)
    REFERENCES `mcfaddan`.`orders` (`orderID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mcfaddan`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`staff` (
  `staffID` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `address1` VARCHAR(255) NULL DEFAULT NULL,
  `address2` VARCHAR(255) NULL DEFAULT NULL,
  `address3` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `eircode` VARCHAR(255) NULL DEFAULT NULL,
  `hireDate` DATE NULL DEFAULT NULL,
  `gender` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `jobTitle` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`staffID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mcfaddan`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mcfaddan`.`wishlist` (
  `wishlistID` INT NOT NULL AUTO_INCREMENT,
  `memberID` INT NULL DEFAULT NULL,
  `productID` INT NULL DEFAULT NULL,
  `dateAdded` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`wishlistID`),
  INDEX `memberID` (`memberID` ASC) VISIBLE,
  INDEX `productID` (`productID` ASC) VISIBLE,
  CONSTRAINT `wishlist_ibfk_1`
    FOREIGN KEY (`memberID`)
    REFERENCES `mcfaddan`.`member` (`memberID`),
  CONSTRAINT `wishlist_ibfk_2`
    FOREIGN KEY (`productID`)
    REFERENCES `mcfaddan`.`product` (`productID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
